server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test-realm
      client:
        provider: # oidc (openID connection) provider
          keycloak:
            issuer-uri: http://localhost:8080/realms/test-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-security
            client-secret: 7Aae20Tjb3hPEkYrnxNu3uXwG3ISg679
            scope: openid
